name: FirstWorkFlow

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
    luna:
      runs-on:
        ubuntu-latest
      steps:
        - run: echo "Hello World"
        - uses: actions/checkout@v3
          with:
            node-version: 22
        - name: traer repositorio 
          run: git clone https://github.com/estebanmendez/Proyecto-Integrador.git
        - uses: actions/setup-node@v4
        - name: instalar dependencias
          run: npm install
        - name: Pasar Lint
          run: npm run lint


  # build-and-test:
  #   runs-on: ubuntu-latest  

  #   steps:
  #   # Configuración básica del pipeline
  #   - name: Checkout Code
  #     uses: actions/checkout@v3

  #   # Configura tu entorno (Node.js, Python, etc.)
  #   - name: Set up Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 16

  #   # Instalar dependencias
  #   - name: Install dependencies
  #     run: npm install

  #   # Correr pruebas
  #   - name: Run tests
  #     run: npm test
